name: domain
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  dartz: ^0.10.1
  freezed: ^2.0.2
  freezed_annotation: ^2.0.1
  get_it: ^7.2.0
  rxdart: ^0.27.3
  shared_preferences: ^2.0.15
  socket_io_client:
    git:
      url: https://github.com/dvasea1/socket.io-client-dart.git
      ref: test_chat

dev_dependencies:
  lints: ^1.0.1
  build_runner:
